import type { Preview } from '@storybook/angular';
import { applicationConfig, componentWrapperDecorator } from '@storybook/angular';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideTranslateService, TranslateLoader, TranslationObject } from '@ngx-translate/core';
import { of, Observable } from 'rxjs';

class StoryTranslateLoader implements TranslateLoader {
  getTranslation(_lang: string): Observable<TranslationObject> {
    return of({
      COMMON: {
        SAVE: 'Save',
        CANCEL: 'Cancel',
        DELETE: 'Delete',
        EDIT: 'Edit',
        CREATE: 'Create',
        SEARCH: 'Search…',
        CLOSE: 'Close',
        CONFIRM: 'Confirm',
        YES: 'Yes',
        NO: 'No',
        LOADING: 'Loading…',
        NO_DATA: 'No data available',
        ACTIONS: 'Actions',
        NAME: 'Name',
        STATUS: 'Status',
        TYPE: 'Type',
        BACK: 'Back',
        NEXT: 'Next',
        PREVIOUS: 'Previous',
        RELOAD: 'Reload',
        FREE: 'Free',
        COLLAPSE_ALL: 'Collapse All',
        EXPAND_ALL: 'Expand All',
        VIEW: 'View',
        ADD: 'Add',
        LANG_EN: 'English',
        LANG_RU: 'Русский',
        LANG_UK: 'Українська',
        LANG_BE: 'Беларуская',
      },
      ARIA: {
        SEARCH: 'Search',
        CLEAR_SEARCH: 'Clear search',
        MENU: 'Menu',
        CLOSE: 'Close',
        BREADCRUMB: 'Breadcrumb navigation',
        TAB_NAVIGATION: 'Tab navigation',
        PROGRESS: 'Progress',
        INLINE_EDIT: 'Click to edit',
        TOGGLE_THEME: 'Toggle theme',
        STEPPER: 'Step navigation',
        DISMISS: 'Dismiss',
        REMOVE: 'Remove',
        LOADING: 'Loading content',
        LANGUAGE_SELECTOR: 'Select language',
        SWITCH_LIGHT: 'Switch to light theme',
        SWITCH_DARK: 'Switch to dark theme',
        SHOW_PASSWORD: 'Show password',
        HIDE_PASSWORD: 'Hide password',
        ROW_ACTIONS: 'Row actions',
        DATA_GRID: 'Data grid',
        EXPAND: 'Expand',
        COLLAPSE: 'Collapse',
      },
      LOGIN: {
        TITLE: 'Sign In',
        USERNAME: 'Username',
        PASSWORD: 'Password',
        SUBMIT: 'Log In',
      },
      STORY: {
        LABEL: 'Example Label',
        HINT: 'This is a hint',
        PLACEHOLDER: 'Enter text…',
        TITLE: 'Story Title',
        SUBTITLE: 'Story Subtitle',
        STEP_1: 'Step 1',
        STEP_2: 'Step 2',
        STEP_3: 'Step 3',
        STEP_4: 'Step 4',
        STEP_5: 'Step 5',
        TAB_ONE: 'Tab One',
        TAB_TWO: 'Tab Two',
        TAB_THREE: 'Tab Three',
        CHIP: 'Example Chip',
        BADGE: 'New',
        HOME: 'Home',
        SECTION: 'Section',
        PAGE: 'Current Page',
        MENU_ITEM_1: 'Menu Item 1',
        MENU_ITEM_2: 'Menu Item 2',
        MENU_ITEM_3: 'Delete',
        PANEL_TITLE: 'Panel Title',
        PANEL_SUBTITLE: 'Panel Subtitle',
        REQUIRED: 'This field is required',
        MIN_LENGTH: 'Minimum length not met',
        PASSWORD_MISMATCH: 'Passwords do not match',
        UPPERCASE_REQUIRED: 'Must contain an uppercase letter',
      },
      UI_LIB: {
        GRID: {
          ARIA_LABEL: 'Data grid',
          PAGE: 'Page',
          OF: 'of',
          TO: 'to',
          MORE: 'More',
          ROWS: 'rows',
          NEXT: 'Next',
          PREVIOUS: 'Previous',
          FIRST: 'First',
          LAST: 'Last',
          NO_ROWS: 'No rows to show',
          LOADING: 'Loading…',
          FILTER: 'Filter…',
          FILTER_OOO: 'Filter…',
          CONTAINS: 'Contains',
          NOT_CONTAINS: 'Not contains',
          EQUALS: 'Equals',
          NOT_EQUAL: 'Not equal',
          LESS_THAN: 'Less than',
          GREATER_THAN: 'Greater than',
          STARTS_WITH: 'Starts with',
          ENDS_WITH: 'Ends with',
          AND: 'And',
          OR: 'Or',
          APPLY_FILTER: 'Apply Filter',
          RESET_FILTER: 'Reset Filter',
          CLEAR_FILTER: 'Clear Filter',
          SELECT_ALL: 'Select All',
          SEARCH: 'Search…',
          SEARCH_OOO: 'Search…',
          BLANKS: '(Blanks)',
          NOT_BLANK: 'Not blank',
          SORT_ASC: 'Sort Ascending',
          SORT_DESC: 'Sort Descending',
          COPY: 'Copy',
          COPY_WITH_HEADERS: 'Copy with Headers',
          PASTE: 'Paste',
          EXPORT: 'Export',
          CSV_EXPORT: 'CSV Export',
          EXCEL_EXPORT: 'Excel Export',
          PINNED: 'Pinned',
          PIN_COLUMN: 'Pin Column',
          PIN_LEFT: 'Pin Left',
          PIN_RIGHT: 'Pin Right',
          NO_PIN: 'No Pin',
          VALUE_AGGREGATION: 'Value Aggregation',
          AUTO_SIZE: 'Auto Size',
          AUTOSIZE_COLUMN: 'Auto Size Column',
          AUTOSIZE_ALL: 'Auto Size All Columns',
          RESET_COLUMNS: 'Reset Columns',
          GROUP: 'Group',
          UNGROUP: 'Ungroup',
          COLUMNS: 'Columns',
          ROW_GROUP_COLUMNS_EMPTY: 'Drag here to group',
          ROW_GROUP_EMPTY: 'Drag here to group',
          PIVOT_COLUMNS_EMPTY: 'Drag here to pivot',
          PIVOT_MODE: 'Pivot Mode',
          VALUES_COLUMNS_EMPTY: 'Drag here to aggregate',
          VALUE_COLUMNS_EMPTY: 'Drag here to aggregate',
          ARIA_FILTER_INPUT: 'Filter input',
          ARIA_PAGE_SIZE: 'Page size',
        },
      },
      LANGUAGES: {
        EN: 'English',
        RU: 'Russian',
        UK: 'Ukrainian',
        BE: 'Belarusian',
      },
    });
  }
}

const preview: Preview = {
  decorators: [
    applicationConfig({
      providers: [
        provideAnimations(),
        provideTranslateService({
          lang: 'en',
          loader: { provide: TranslateLoader, useClass: StoryTranslateLoader },
        }),
      ],
    }),
    componentWrapperDecorator(
      (story) => `<div class="theme-light">${story}</div>`
    ),
  ],
  parameters: {
    backgrounds: {
      default: 'light',
      values: [
        { name: 'light', value: '#f5f5f5' },
        { name: 'dark', value: '#1e1e1e' },
      ],
    },
  },
};

export default preview;
